### ISSUE TITLE
Logs not enabled

### ISSUE THREAD

**Issue by taik0** [deric/puppet-mesos#44]
The LOGS_DIR has no effect. If you take a look at the wrapper (at least for ubuntu) the only variable that has effect it's LOGS (which it's commented).

```
# This file is managed by Puppet

# enables mesos logging, otherwise stdout goes to LOG_DIR
#LOGS=/var/log/mesos
# both master and slave will log into syslog file
USE_SYSLOG="<%= @use_syslog %>"
# separate 'master.log' and 'slave.log' files
LOG_DIR="<%= @log_dir %>"
```

From the mesos-init-wrapper:
```
[[ ! ${LOGS:-} ]]           || args+=( --log_dir="$LOGS" )
```

**Comment by deric** [comment]
Right, I guess we can set the `LOGS` variable, but by default it will be undefined, so that we won't break current installations. Is that ok for you?

**Comment by taik0** [comment]
Of course, It was just that I didn't know what was happening. Thank you!
