### ISSUE TITLE
mesos::masters::options and mesos::slave::options conflict on machine that is both master and slave

### ISSUE THREAD

**Issue by ianburrell** [deric/puppet-mesos#45]
We are running the mesos slave on the mesos master machine. The config looks like:

```
  class { '::mesos::master':
    options => {
      quorum => 2,
      quiet => true,
     },
  }
 
  class { '::mesos::slave':
    options => {
      gc_disk_headroom => '0.1',
      quiet => true,
    },
}
```
This causes an error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Mesos::Property[quiet] is already declared; cannot redeclare at /etc/puppet/environments/production/modules/mesos/manifests/master.pp:61 on node lindevspark1.vw.rentrak.com

The cause is that mesos::master and mesos::slave use mesos::property for options with the option names. The resource names conflict even though they are separate config files. It looks like the static mesos::property are prefixes (master_work_dir, slave_work_dir).

It looks likes mesos_hash_parser can already add prefix, but it is also applied to the file. Would need to way to override the "file" with the hash name.

**Comment by deric** [comment]
Fixed in #48. Thanks Ian!
