### ISSUE TITLE
undef property specs failing with new rspec

### ISSUE THREAD

**Issue by deric** [deric/puppet-mesos#70]
`mesos::property` spec with `:undef` added in 5e48338d79e6ff0a3d9cd323b0764204f9f38bcc are failing with `STRICT_VARIABLES` on [Puppet 3](https://travis-ci.org/deric/puppet-mesos/builds/119468799).
```
 Undefined variable "value" at /home/travis/build/deric/puppet-mesos/spec/fixtures/modules/mesos/manifests/property.pp:27
     # ./spec/defines/property_spec.rb:52:in `block (3 levels) in <top (required)>'
```

The syntax should be correct, it was introduced [here](https://github.com/rodjek/rspec-puppet/pull/335).

**Comment by deric** [comment]
@JayH5 any ideas?

**Comment by JayH5** [comment]
@deric: :cry: I don't really know. This rspec + Puppet stuff is often quite fragile. Sorry, I don't really have time to dig into this at the moment... Can maybe take a look next week.

**Comment by deric** [comment]
@JayH5 Sure, no problem. Downgrading `rspec-puppet` to `< 2.4.0` seems to resolve the problem. So the problem was probably introduced somewhere here [v2.3.2...v2.4.0](https://github.com/rodjek/rspec-puppet/compare/v2.3.2...v2.4.0).
