### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by akhld** [deric/puppet-mesos#71]
Couple of things are missing from the documentation:

- Instruction to run the project
- What to expect when you run it

Can someone post screenshots or execution command of the same?

**Comment by deric** [comment]
Not sure if I understand what do you mean. Installation of the module is the same as for any puppet module:
```
puppet module install deric-mesos
```
Have a look on some tutorials, e.g. [here](https://www.digitalocean.com/community/tutorials/getting-started-with-puppet-code-manifests-and-modules).

After including master or slave declaration:
```puppet
class{'mesos::master':
  options => {
    quorum   => 2
  }
}
```
You should expect that `mesos` package will be installed and `mesos-master` service configured.

**Comment by akhld** [comment]
Thanks. I'm new to puppet.
