### ISSUE TITLE
Different behavior with mesos 0.28.1 and 0.28.2

### ISSUE THREAD

**Issue by nhaumont** [deric/puppet-mesos#72]
Hi,

We use the mesos module with the 0.28.1 without issues and the mesos master and slave services can start without pb once installed. But when using it with the 0.28.2, I have the issue that the mesos-slave service cannot be started because of this error:

```
 Failed to load unknown flag 'work_dir.rpmnew'
```

When checking in `/etc/mesos-slave`, only `work_dir` exists for the 0.28.1
But with 0.28.2, we have `work_dir` and `work_dir.rpmnew`, which seems to cause some trouble.

Thanks,
Nicolas

**Comment by deric** [comment]
Which distribution do you use? Is it RedHat based? What does file `/etc/default/mesos-slave` contain?

**Comment by deric** [comment]
Btw. there's `purge = true` set on `/etc/mesos-slave`, so any files created by a package manager should be deleted on next run.

**Comment by deric** [comment]
Should be fixed by #79. Please reopen if the problem persists.
