### ISSUE TITLE
Failure to start service on RHEL6

### ISSUE THREAD

**Issue by wleese** [deric/puppet-mesos#8]
Hi,

I already submitted a PR to work around this piece of code for RHEL7:

```
  if $::osfamily == 'RedHat' and $::os_maj_version < 7 { 
    $provider = 'upstart'
  } else {
    $provider = undef
  }
  service { "mesos-${name}":
    ensure     => 'running',
    hasstatus  => true,
    hasrestart => true,
    enable     => $enable,
    provider   => $provider,
    subscribe  => [ File['/etc/default/mesos'],
      File["/etc/default/mesos-${name}"]
    ],  
  }
```

..but now with testing RHEL6 I run into:

```
Error: /Stage[main]/Mesos::Master/Mesos::Service[master]/Service[mesos-master]: Provider upstart is not functional on this host
```

..which makes sense considering: https://projects.puppetlabs.com/issues/11989

So my question is what was intended with the $provider juggling? Rather than making things work for RHEL6, it actually prevents successful puppetruns.

The solution seems to be adding a sysvinit style initscript to the module and using that for osfamily=redhat and os_maj_version < 7 and the upstart script only for the ubuntu osfamily. 
Alternatively, we could give the service resource start/stop arguments like mentioned in the bug, which would remove the need for the sysvinit initscript.

Let me know what you think and I'll create a PR along those lines.

**Comment by henricook** [comment]
Hi all, i'm having this problem - is there something more recent than deric/mesos i should be using?

**Comment by deric** [comment]
It depends on your package. You're using rpm from mesosphere? You can solve it by:
```puppet
class { 'mesos::master':
  force_provider => 'upstart' # or 'init', 'systemd' whatever is included in your package
}
```
It's a problem of bad packaging which does not respect conventions on a given OS, we can't handle this within a Puppet module.
