### ISSUE TITLE
Feature request (mesos-master) - systemd : After / Wants

### ISSUE THREAD

**Issue by tamama** [deric/puppet-mesos#80]
Hi there,

May I kindly request if we can have an option to define After and Wants for mesos-master systemd?

Reason: I want it to start after zookeeper-server.service openvpn-client@.service - the latter is because I want to bind everything to the vpn interface only.

Kind regards,
Tamama

**Comment by deric** [comment]
Implemented in `master` branch. Something like:
```puppet
class{'mesos::master':
  service_provider    => 'systemd',
  manage_service_file => true,
  systemd_wants       => 'network.target zookeeper-server.service',
  systemd_after       => 'network.target zookeeper-service.service',
}
```
should work.

**Comment by tamama** [comment]
Thank you so much.
This works perfectly on my cluster.

Kind regards,
Tamama
