### ISSUE TITLE
$zk_session_timeout

### ISSUE THREAD

**Issue by tamama** [deric/puppet-mesos#81]
Hi there, 
Greetings,

May I know what is the best practice here to add an --zk_session_timeout option when starting the Mesos master?

Kind regards,
Tamama

**Comment by deric** [comment]
Typically via options:
```puppet
class{'mesos::master':
  options => {
    zk_session_timeout => 20
  }
}
```
or via hiera config:
```yaml
mesos::master::options:
    zk_session_timeout: 20 
```

**Comment by tamama** [comment]
Though I figured that out sometime ago from your source code, I thank you for confirming the answer. :)
