### ISSUE TITLE
Support for puppetlabs-apt >= 3.0.0

### ISSUE THREAD

**Issue by madelaney** [deric/puppet-mesos#86]
I'd like to be able to use this module, however, the version restriction on puppetlabs-apt is blocking me as modules are using version 3.0.0 or newer.

**Comment by madelaney** [comment]
I'd be happy to do a pull-request, if you'd accept the change.

**Comment by deric** [comment]
@madelaney Hi, have a look at [1.x branch](https://github.com/deric/puppet-mesos/compare/1.x) and let me know if that works for you. I assume you're using Puppet 4, right?

**Comment by madelaney** [comment]
@deric , That looks like it should do it; just based on [metadata.json](https://github.com/deric/puppet-mesos/compare/1.x#diff-490694a9db8f7a371538da1abe484314)

**Comment by deric** [comment]
Tests are failing on Puppet 5, Puppet 4 should be ok. But a patch for older facter might be necessary - that's why I haven't released it yet.

**Comment by madelaney** [comment]
Prior to seeing your first reply, I was able to get tests working on Puppet 4.3 (which should also work in Puppet 5.x).

I'll push my changes to my fork, so you can take a look; I did introduce a new gem. Feel free to use/ignore.

**Comment by madelaney** [comment]
@deric , I pushed my [change](https://github.com/madelaney/puppet-mesos/commit/ff06933080ae5d3573b255058f0cbe96fa50da9b) to my work that supports Puppet 4.x and 5.x. The test ran cleanly on my machine (macOS) but they should run fine.
