### ISSUE TITLE
Centos/RH repo issue

### ISSUE THREAD

**Issue by anesterova** [deric/puppet-mesos#90]
https://github.com/deric/puppet-mesos/blob/v1.0.1/manifests/repo.pp#L79

`source   => "https://repos.mesosphere.io/el/${osrel}/noarch/RPMS/mesosphere-el-repo-${osrel}-${mrel}.noarch.rpm"
`

The latest Centos version is 7.6 while repo version is 7.3 which leads to:

```Error: Execution of '/bin/rpm -i https://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-6.noarch.rpm' returned 1: curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-6.noarch.rpm - transfer failed
Error: /Stage[main]/Mesos::Repo/Package[mesosphere-el-repo]/ensure: change from absent to present failed: Execution of '/bin/rpm -i https://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-6.noar
ch.rpm' returned 1: curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-6.noarch.rpm - transfer failed
```

Maybe ${mrel} should be replaced with another variable / add a check or replace Package with Yumrepo?

**Comment by deric** [comment]
Should be resolved in [v1.1.0](https://github.com/deric/puppet-mesos/releases/tag/v1.1.0). Note: Mesosphere no longer add support for new CentOS/RedHat releases.
