### ISSUE TITLE
There is currently no way to not configure the repo

### ISSUE THREAD

**Issue by dnlsng** [deric/puppet-mesos#93]
Since the default repo was changed to 'mesosphere', you can no longer not manage the repo as you can't pass an undef value to a class parameter in Puppet. An easy fix for this might be to just accept the Boolean type for the $repo parameter so that setting it to false is accepted.

**Comment by deric** [comment]
@dnlsng I feel like allowing types like `Variant[String,Hash,Boolean]` is unnecessary Puppet's type system abuse. I've added parameter:
```
mesos::manage_repo: false
```

**Comment by dnlsng** [comment]
That works for me :).

**Comment by deric** [comment]
Resolved in [`v1.1.0`](https://github.com/deric/puppet-mesos/releases/tag/v1.1.0).
